// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRoundTripper creates a new instance of MockRoundTripper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoundTripper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoundTripper {
	mock := &MockRoundTripper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoundTripper is an autogenerated mock type for the RoundTripper type
type MockRoundTripper struct {
	mock.Mock
}

type MockRoundTripper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoundTripper) EXPECT() *MockRoundTripper_Expecter {
	return &MockRoundTripper_Expecter{mock: &_m.Mock}
}

// RoundTrip provides a mock function for the type MockRoundTripper
func (_mock *MockRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for RoundTrip")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoundTripper_RoundTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoundTrip'
type MockRoundTripper_RoundTrip_Call struct {
	*mock.Call
}

// RoundTrip is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockRoundTripper_Expecter) RoundTrip(req interface{}) *MockRoundTripper_RoundTrip_Call {
	return &MockRoundTripper_RoundTrip_Call{Call: _e.mock.On("RoundTrip", req)}
}

func (_c *MockRoundTripper_RoundTrip_Call) Run(run func(req *http.Request)) *MockRoundTripper_RoundTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoundTripper_RoundTrip_Call) Return(response *http.Response, err error) *MockRoundTripper_RoundTrip_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockRoundTripper_RoundTrip_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockRoundTripper_RoundTrip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAgentGenerator creates a new instance of MockUserAgentGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAgentGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAgentGenerator {
	mock := &MockUserAgentGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAgentGenerator is an autogenerated mock type for the UserAgentGenerator type
type MockUserAgentGenerator struct {
	mock.Mock
}

type MockUserAgentGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAgentGenerator) EXPECT() *MockUserAgentGenerator_Expecter {
	return &MockUserAgentGenerator_Expecter{mock: &_m.Mock}
}

// RandomUserAgent provides a mock function for the type MockUserAgentGenerator
func (_mock *MockUserAgentGenerator) RandomUserAgent() (string, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RandomUserAgent")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (string, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockUserAgentGenerator_RandomUserAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomUserAgent'
type MockUserAgentGenerator_RandomUserAgent_Call struct {
	*mock.Call
}

// RandomUserAgent is a helper method to define mock.On call
func (_e *MockUserAgentGenerator_Expecter) RandomUserAgent() *MockUserAgentGenerator_RandomUserAgent_Call {
	return &MockUserAgentGenerator_RandomUserAgent_Call{Call: _e.mock.On("RandomUserAgent")}
}

func (_c *MockUserAgentGenerator_RandomUserAgent_Call) Run(run func()) *MockUserAgentGenerator_RandomUserAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserAgentGenerator_RandomUserAgent_Call) Return(s string, b bool) *MockUserAgentGenerator_RandomUserAgent_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockUserAgentGenerator_RandomUserAgent_Call) RunAndReturn(run func() (string, bool)) *MockUserAgentGenerator_RandomUserAgent_Call {
	_c.Call.Return(run)
	return _c
}
