// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portgen

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// RandomPort provides a mock function for the type MockGenerator
func (_mock *MockGenerator) RandomPort(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RandomPort")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_RandomPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomPort'
type MockGenerator_RandomPort_Call struct {
	*mock.Call
}

// RandomPort is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGenerator_Expecter) RandomPort(ctx interface{}) *MockGenerator_RandomPort_Call {
	return &MockGenerator_RandomPort_Call{Call: _e.mock.On("RandomPort", ctx)}
}

func (_c *MockGenerator_RandomPort_Call) Run(run func(ctx context.Context)) *MockGenerator_RandomPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenerator_RandomPort_Call) Return(port int, err error) *MockGenerator_RandomPort_Call {
	_c.Call.Return(port, err)
	return _c
}

func (_c *MockGenerator_RandomPort_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockGenerator_RandomPort_Call {
	_c.Call.Return(run)
	return _c
}
