// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mmdb

import (
	"net/http"
	"net/netip"

	"github.com/oschwald/geoip2-golang/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGeoReader creates a new instance of MockGeoReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeoReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeoReader {
	mock := &MockGeoReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeoReader is an autogenerated mock type for the GeoReader type
type MockGeoReader struct {
	mock.Mock
}

type MockGeoReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeoReader) EXPECT() *MockGeoReader_Expecter {
	return &MockGeoReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockGeoReader
func (_mock *MockGeoReader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGeoReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockGeoReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockGeoReader_Expecter) Close() *MockGeoReader_Close_Call {
	return &MockGeoReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockGeoReader_Close_Call) Run(run func()) *MockGeoReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGeoReader_Close_Call) Return(err error) *MockGeoReader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGeoReader_Close_Call) RunAndReturn(run func() error) *MockGeoReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Country provides a mock function for the type MockGeoReader
func (_mock *MockGeoReader) Country(addr netip.Addr) (*geoip2.Country, error) {
	ret := _mock.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Country")
	}

	var r0 *geoip2.Country
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(netip.Addr) (*geoip2.Country, error)); ok {
		return returnFunc(addr)
	}
	if returnFunc, ok := ret.Get(0).(func(netip.Addr) *geoip2.Country); ok {
		r0 = returnFunc(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*geoip2.Country)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(netip.Addr) error); ok {
		r1 = returnFunc(addr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeoReader_Country_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Country'
type MockGeoReader_Country_Call struct {
	*mock.Call
}

// Country is a helper method to define mock.On call
//   - addr netip.Addr
func (_e *MockGeoReader_Expecter) Country(addr interface{}) *MockGeoReader_Country_Call {
	return &MockGeoReader_Country_Call{Call: _e.mock.On("Country", addr)}
}

func (_c *MockGeoReader_Country_Call) Run(run func(addr netip.Addr)) *MockGeoReader_Country_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 netip.Addr
		if args[0] != nil {
			arg0 = args[0].(netip.Addr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGeoReader_Country_Call) Return(country *geoip2.Country, err error) *MockGeoReader_Country_Call {
	_c.Call.Return(country, err)
	return _c
}

func (_c *MockGeoReader_Country_Call) RunAndReturn(run func(addr netip.Addr) (*geoip2.Country, error)) *MockGeoReader_Country_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPDoer creates a new instance of MockHTTPDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPDoer {
	mock := &MockHTTPDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPDoer is an autogenerated mock type for the HTTPDoer type
type MockHTTPDoer struct {
	mock.Mock
}

type MockHTTPDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPDoer) EXPECT() *MockHTTPDoer_Expecter {
	return &MockHTTPDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockHTTPDoer
func (_mock *MockHTTPDoer) Do(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHTTPDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockHTTPDoer_Expecter) Do(req interface{}) *MockHTTPDoer_Do_Call {
	return &MockHTTPDoer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockHTTPDoer_Do_Call) Run(run func(req *http.Request)) *MockHTTPDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHTTPDoer_Do_Call) Return(response *http.Response, err error) *MockHTTPDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPDoer_Do_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockHTTPDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}
