force-file-write: true

packages:
  github.com/denisdubovitskiy/vpnconfig/internal/command:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      Executor:

  github.com/denisdubovitskiy/vpnconfig/internal/singboxcli:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      ConfigValidator:
      CommandExecutor:

  github.com/denisdubovitskiy/vpnconfig/internal/profile/happ:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      Doer:

  github.com/denisdubovitskiy/vpnconfig/internal/profile/plaintext:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      Doer:

  github.com/denisdubovitskiy/vpnconfig/internal/resolver:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      IPResolver:

  github.com/denisdubovitskiy/vpnconfig/internal/http:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      RoundTripper:
      UserAgentGenerator:

  github.com/denisdubovitskiy/vpnconfig/internal/ipserv:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      IPLookup:

  github.com/denisdubovitskiy/vpnconfig/internal/ipserv/mmdb:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      GeoReader:
      HTTPDoer:

  github.com/denisdubovitskiy/vpnconfig/internal/useragent:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      Rand:

  github.com/denisdubovitskiy/vpnconfig/internal/vpnurl:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      SchemeParser:

  github.com/denisdubovitskiy/vpnconfig/internal/updater:
    config:
      filename: zzz_mocks_test.go
    interfaces:
      LinkFetcher:
      GeoIPService:
      VPNParser:
      ConfigStore:
      ConfigValidator:
