// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package singboxcli

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigValidator creates a new instance of MockConfigValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigValidator {
	mock := &MockConfigValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigValidator is an autogenerated mock type for the ConfigValidator type
type MockConfigValidator struct {
	mock.Mock
}

type MockConfigValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigValidator) EXPECT() *MockConfigValidator_Expecter {
	return &MockConfigValidator_Expecter{mock: &_m.Mock}
}

// CheckConfig provides a mock function for the type MockConfigValidator
func (_mock *MockConfigValidator) CheckConfig(ctx context.Context, configPath string) error {
	ret := _mock.Called(ctx, configPath)

	if len(ret) == 0 {
		panic("no return value specified for CheckConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, configPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigValidator_CheckConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckConfig'
type MockConfigValidator_CheckConfig_Call struct {
	*mock.Call
}

// CheckConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - configPath string
func (_e *MockConfigValidator_Expecter) CheckConfig(ctx interface{}, configPath interface{}) *MockConfigValidator_CheckConfig_Call {
	return &MockConfigValidator_CheckConfig_Call{Call: _e.mock.On("CheckConfig", ctx, configPath)}
}

func (_c *MockConfigValidator_CheckConfig_Call) Run(run func(ctx context.Context, configPath string)) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigValidator_CheckConfig_Call) Return(err error) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigValidator_CheckConfig_Call) RunAndReturn(run func(ctx context.Context, configPath string) error) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandExecutor creates a new instance of MockCommandExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandExecutor {
	mock := &MockCommandExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandExecutor is an autogenerated mock type for the CommandExecutor type
type MockCommandExecutor struct {
	mock.Mock
}

type MockCommandExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandExecutor) EXPECT() *MockCommandExecutor_Expecter {
	return &MockCommandExecutor_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockCommandExecutor
func (_mock *MockCommandExecutor) Exec(ctx context.Context, name string, arg ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(arg) > 0 {
		tmpRet = _mock.Called(ctx, name, arg)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, name, arg...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, arg...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandExecutor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCommandExecutor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - arg ...string
func (_e *MockCommandExecutor_Expecter) Exec(ctx interface{}, name interface{}, arg ...interface{}) *MockCommandExecutor_Exec_Call {
	return &MockCommandExecutor_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, name}, arg...)...)}
}

func (_c *MockCommandExecutor_Exec_Call) Run(run func(ctx context.Context, name string, arg ...string)) *MockCommandExecutor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCommandExecutor_Exec_Call) Return(bytes []byte, err error) *MockCommandExecutor_Exec_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCommandExecutor_Exec_Call) RunAndReturn(run func(ctx context.Context, name string, arg ...string) ([]byte, error)) *MockCommandExecutor_Exec_Call {
	_c.Call.Return(run)
	return _c
}
