// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package checker

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSingBoxRunner creates a new instance of MockSingBoxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSingBoxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSingBoxRunner {
	mock := &MockSingBoxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSingBoxRunner is an autogenerated mock type for the SingBoxRunner type
type MockSingBoxRunner struct {
	mock.Mock
}

type MockSingBoxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSingBoxRunner) EXPECT() *MockSingBoxRunner_Expecter {
	return &MockSingBoxRunner_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockSingBoxRunner
func (_mock *MockSingBoxRunner) Start(ctx context.Context, configPath string, port int) error {
	ret := _mock.Called(ctx, configPath, port)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, configPath, port)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSingBoxRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSingBoxRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - configPath string
//   - port int
func (_e *MockSingBoxRunner_Expecter) Start(ctx interface{}, configPath interface{}, port interface{}) *MockSingBoxRunner_Start_Call {
	return &MockSingBoxRunner_Start_Call{Call: _e.mock.On("Start", ctx, configPath, port)}
}

func (_c *MockSingBoxRunner_Start_Call) Run(run func(ctx context.Context, configPath string, port int)) *MockSingBoxRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSingBoxRunner_Start_Call) Return(err error) *MockSingBoxRunner_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSingBoxRunner_Start_Call) RunAndReturn(run func(ctx context.Context, configPath string, port int) error) *MockSingBoxRunner_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockSingBoxRunner
func (_mock *MockSingBoxRunner) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSingBoxRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockSingBoxRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSingBoxRunner_Expecter) Stop(ctx interface{}) *MockSingBoxRunner_Stop_Call {
	return &MockSingBoxRunner_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockSingBoxRunner_Stop_Call) Run(run func(ctx context.Context)) *MockSingBoxRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSingBoxRunner_Stop_Call) Return(err error) *MockSingBoxRunner_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSingBoxRunner_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockSingBoxRunner_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// CheckLink provides a mock function for the type MockChecker
func (_mock *MockChecker) CheckLink(ctx context.Context, vlessLink string) error {
	ret := _mock.Called(ctx, vlessLink)

	if len(ret) == 0 {
		panic("no return value specified for CheckLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, vlessLink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChecker_CheckLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLink'
type MockChecker_CheckLink_Call struct {
	*mock.Call
}

// CheckLink is a helper method to define mock.On call
//   - ctx context.Context
//   - vlessLink string
func (_e *MockChecker_Expecter) CheckLink(ctx interface{}, vlessLink interface{}) *MockChecker_CheckLink_Call {
	return &MockChecker_CheckLink_Call{Call: _e.mock.On("CheckLink", ctx, vlessLink)}
}

func (_c *MockChecker_CheckLink_Call) Run(run func(ctx context.Context, vlessLink string)) *MockChecker_CheckLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChecker_CheckLink_Call) Return(err error) *MockChecker_CheckLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChecker_CheckLink_Call) RunAndReturn(run func(ctx context.Context, vlessLink string) error) *MockChecker_CheckLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHttpDoer creates a new instance of MockHttpDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHttpDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHttpDoer {
	mock := &MockHttpDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHttpDoer is an autogenerated mock type for the HttpDoer type
type MockHttpDoer struct {
	mock.Mock
}

type MockHttpDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHttpDoer) EXPECT() *MockHttpDoer_Expecter {
	return &MockHttpDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockHttpDoer
func (_mock *MockHttpDoer) Do(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHttpDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHttpDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockHttpDoer_Expecter) Do(req interface{}) *MockHttpDoer_Do_Call {
	return &MockHttpDoer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockHttpDoer_Do_Call) Run(run func(req *http.Request)) *MockHttpDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHttpDoer_Do_Call) Return(response *http.Response, err error) *MockHttpDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHttpDoer_Do_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockHttpDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPortGenerator creates a new instance of MockPortGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortGenerator {
	mock := &MockPortGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortGenerator is an autogenerated mock type for the PortGenerator type
type MockPortGenerator struct {
	mock.Mock
}

type MockPortGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortGenerator) EXPECT() *MockPortGenerator_Expecter {
	return &MockPortGenerator_Expecter{mock: &_m.Mock}
}

// RandomPort provides a mock function for the type MockPortGenerator
func (_mock *MockPortGenerator) RandomPort(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RandomPort")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortGenerator_RandomPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RandomPort'
type MockPortGenerator_RandomPort_Call struct {
	*mock.Call
}

// RandomPort is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPortGenerator_Expecter) RandomPort(ctx interface{}) *MockPortGenerator_RandomPort_Call {
	return &MockPortGenerator_RandomPort_Call{Call: _e.mock.On("RandomPort", ctx)}
}

func (_c *MockPortGenerator_RandomPort_Call) Run(run func(ctx context.Context)) *MockPortGenerator_RandomPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPortGenerator_RandomPort_Call) Return(port int, err error) *MockPortGenerator_RandomPort_Call {
	_c.Call.Return(port, err)
	return _c
}

func (_c *MockPortGenerator_RandomPort_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockPortGenerator_RandomPort_Call {
	_c.Call.Return(run)
	return _c
}
