// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package vpnurl

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSchemeParser creates a new instance of MockSchemeParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchemeParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchemeParser {
	mock := &MockSchemeParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSchemeParser is an autogenerated mock type for the SchemeParser type
type MockSchemeParser struct {
	mock.Mock
}

type MockSchemeParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchemeParser) EXPECT() *MockSchemeParser_Expecter {
	return &MockSchemeParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockSchemeParser
func (_mock *MockSchemeParser) Parse(vpnURL string) (SingBoxOutbound, error) {
	ret := _mock.Called(vpnURL)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 SingBoxOutbound
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (SingBoxOutbound, error)); ok {
		return returnFunc(vpnURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) SingBoxOutbound); ok {
		r0 = returnFunc(vpnURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SingBoxOutbound)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(vpnURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSchemeParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockSchemeParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - vpnURL string
func (_e *MockSchemeParser_Expecter) Parse(vpnURL interface{}) *MockSchemeParser_Parse_Call {
	return &MockSchemeParser_Parse_Call{Call: _e.mock.On("Parse", vpnURL)}
}

func (_c *MockSchemeParser_Parse_Call) Run(run func(vpnURL string)) *MockSchemeParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSchemeParser_Parse_Call) Return(singBoxOutbound SingBoxOutbound, err error) *MockSchemeParser_Parse_Call {
	_c.Call.Return(singBoxOutbound, err)
	return _c
}

func (_c *MockSchemeParser_Parse_Call) RunAndReturn(run func(vpnURL string) (SingBoxOutbound, error)) *MockSchemeParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
