// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ipserv

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPLookup creates a new instance of MockIPLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPLookup {
	mock := &MockIPLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPLookup is an autogenerated mock type for the IPLookup type
type MockIPLookup struct {
	mock.Mock
}

type MockIPLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPLookup) EXPECT() *MockIPLookup_Expecter {
	return &MockIPLookup_Expecter{mock: &_m.Mock}
}

// CountryByIP provides a mock function for the type MockIPLookup
func (_mock *MockIPLookup) CountryByIP(ctx context.Context, ip string) (*Location, error) {
	ret := _mock.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for CountryByIP")
	}

	var r0 *Location
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Location, error)); ok {
		return returnFunc(ctx, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Location); ok {
		r0 = returnFunc(ctx, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Location)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPLookup_CountryByIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountryByIP'
type MockIPLookup_CountryByIP_Call struct {
	*mock.Call
}

// CountryByIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *MockIPLookup_Expecter) CountryByIP(ctx interface{}, ip interface{}) *MockIPLookup_CountryByIP_Call {
	return &MockIPLookup_CountryByIP_Call{Call: _e.mock.On("CountryByIP", ctx, ip)}
}

func (_c *MockIPLookup_CountryByIP_Call) Run(run func(ctx context.Context, ip string)) *MockIPLookup_CountryByIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPLookup_CountryByIP_Call) Return(location *Location, err error) *MockIPLookup_CountryByIP_Call {
	_c.Call.Return(location, err)
	return _c
}

func (_c *MockIPLookup_CountryByIP_Call) RunAndReturn(run func(ctx context.Context, ip string) (*Location, error)) *MockIPLookup_CountryByIP_Call {
	_c.Call.Return(run)
	return _c
}
