// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resolver

import (
	"context"
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPResolver creates a new instance of MockIPResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPResolver {
	mock := &MockIPResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPResolver is an autogenerated mock type for the IPResolver type
type MockIPResolver struct {
	mock.Mock
}

type MockIPResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPResolver) EXPECT() *MockIPResolver_Expecter {
	return &MockIPResolver_Expecter{mock: &_m.Mock}
}

// LookupIP provides a mock function for the type MockIPResolver
func (_mock *MockIPResolver) LookupIP(ctx context.Context, network string, host string) ([]net.IP, error) {
	ret := _mock.Called(ctx, network, host)

	if len(ret) == 0 {
		panic("no return value specified for LookupIP")
	}

	var r0 []net.IP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]net.IP, error)); ok {
		return returnFunc(ctx, network, host)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []net.IP); ok {
		r0 = returnFunc(ctx, network, host)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.IP)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, network, host)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPResolver_LookupIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupIP'
type MockIPResolver_LookupIP_Call struct {
	*mock.Call
}

// LookupIP is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - host string
func (_e *MockIPResolver_Expecter) LookupIP(ctx interface{}, network interface{}, host interface{}) *MockIPResolver_LookupIP_Call {
	return &MockIPResolver_LookupIP_Call{Call: _e.mock.On("LookupIP", ctx, network, host)}
}

func (_c *MockIPResolver_LookupIP_Call) Run(run func(ctx context.Context, network string, host string)) *MockIPResolver_LookupIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPResolver_LookupIP_Call) Return(iPs []net.IP, err error) *MockIPResolver_LookupIP_Call {
	_c.Call.Return(iPs, err)
	return _c
}

func (_c *MockIPResolver_LookupIP_Call) RunAndReturn(run func(ctx context.Context, network string, host string) ([]net.IP, error)) *MockIPResolver_LookupIP_Call {
	_c.Call.Return(run)
	return _c
}
