// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package command

import (
	"context"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Exec(ctx context.Context, name string, arg ...string) ([]byte, error) {
	var tmpRet mock.Arguments
	if len(arg) > 0 {
		tmpRet = _mock.Called(ctx, name, arg)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]byte, error)); ok {
		return returnFunc(ctx, name, arg...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []byte); ok {
		r0 = returnFunc(ctx, name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, arg...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockExecutor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - arg ...string
func (_e *MockExecutor_Expecter) Exec(ctx interface{}, name interface{}, arg ...interface{}) *MockExecutor_Exec_Call {
	return &MockExecutor_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{ctx, name}, arg...)...)}
}

func (_c *MockExecutor_Exec_Call) Run(run func(ctx context.Context, name string, arg ...string)) *MockExecutor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockExecutor_Exec_Call) Return(bytes []byte, err error) *MockExecutor_Exec_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockExecutor_Exec_Call) RunAndReturn(run func(ctx context.Context, name string, arg ...string) ([]byte, error)) *MockExecutor_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand {
	mock := &MockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

type MockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommand) EXPECT() *MockCommand_Expecter {
	return &MockCommand_Expecter{mock: &_m.Mock}
}

// Kill provides a mock function for the type MockCommand
func (_mock *MockCommand) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockCommand_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Kill() *MockCommand_Kill_Call {
	return &MockCommand_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockCommand_Kill_Call) Run(run func()) *MockCommand_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Kill_Call) Return(err error) *MockCommand_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Kill_Call) RunAndReturn(run func() error) *MockCommand_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Signal provides a mock function for the type MockCommand
func (_mock *MockCommand) Signal(sig os.Signal) error {
	ret := _mock.Called(sig)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(os.Signal) error); ok {
		r0 = returnFunc(sig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockCommand_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - sig os.Signal
func (_e *MockCommand_Expecter) Signal(sig interface{}) *MockCommand_Signal_Call {
	return &MockCommand_Signal_Call{Call: _e.mock.On("Signal", sig)}
}

func (_c *MockCommand_Signal_Call) Run(run func(sig os.Signal)) *MockCommand_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 os.Signal
		if args[0] != nil {
			arg0 = args[0].(os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommand_Signal_Call) Return(err error) *MockCommand_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Signal_Call) RunAndReturn(run func(sig os.Signal) error) *MockCommand_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockCommand
func (_mock *MockCommand) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCommand_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCommand_Expecter) Start(ctx interface{}) *MockCommand_Start_Call {
	return &MockCommand_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockCommand_Start_Call) Run(run func(ctx context.Context)) *MockCommand_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommand_Start_Call) Return(err error) *MockCommand_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockCommand_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stderr provides a mock function for the type MockCommand
func (_mock *MockCommand) Stderr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stderr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_Stderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stderr'
type MockCommand_Stderr_Call struct {
	*mock.Call
}

// Stderr is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Stderr() *MockCommand_Stderr_Call {
	return &MockCommand_Stderr_Call{Call: _e.mock.On("Stderr")}
}

func (_c *MockCommand_Stderr_Call) Run(run func()) *MockCommand_Stderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Stderr_Call) Return(s string) *MockCommand_Stderr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_Stderr_Call) RunAndReturn(run func() string) *MockCommand_Stderr_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockCommand
func (_mock *MockCommand) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommand_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockCommand_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Wait() *MockCommand_Wait_Call {
	return &MockCommand_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockCommand_Wait_Call) Run(run func()) *MockCommand_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Wait_Call) Return(err error) *MockCommand_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommand_Wait_Call) RunAndReturn(run func() error) *MockCommand_Wait_Call {
	_c.Call.Return(run)
	return _c
}
