// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package updater

import (
	"context"

	"github.com/denisdubovitskiy/vpnconfig/internal/singbox"
	"github.com/denisdubovitskiy/vpnconfig/internal/vpnurl"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkFetcher creates a new instance of MockLinkFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkFetcher {
	mock := &MockLinkFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkFetcher is an autogenerated mock type for the LinkFetcher type
type MockLinkFetcher struct {
	mock.Mock
}

type MockLinkFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkFetcher) EXPECT() *MockLinkFetcher_Expecter {
	return &MockLinkFetcher_Expecter{mock: &_m.Mock}
}

// FetchLinks provides a mock function for the type MockLinkFetcher
func (_mock *MockLinkFetcher) FetchLinks(ctx context.Context, url string) ([]string, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for FetchLinks")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkFetcher_FetchLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchLinks'
type MockLinkFetcher_FetchLinks_Call struct {
	*mock.Call
}

// FetchLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockLinkFetcher_Expecter) FetchLinks(ctx interface{}, url interface{}) *MockLinkFetcher_FetchLinks_Call {
	return &MockLinkFetcher_FetchLinks_Call{Call: _e.mock.On("FetchLinks", ctx, url)}
}

func (_c *MockLinkFetcher_FetchLinks_Call) Run(run func(ctx context.Context, url string)) *MockLinkFetcher_FetchLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkFetcher_FetchLinks_Call) Return(strings []string, err error) *MockLinkFetcher_FetchLinks_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLinkFetcher_FetchLinks_Call) RunAndReturn(run func(ctx context.Context, url string) ([]string, error)) *MockLinkFetcher_FetchLinks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGeoIPService creates a new instance of MockGeoIPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeoIPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeoIPService {
	mock := &MockGeoIPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeoIPService is an autogenerated mock type for the GeoIPService type
type MockGeoIPService struct {
	mock.Mock
}

type MockGeoIPService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeoIPService) EXPECT() *MockGeoIPService_Expecter {
	return &MockGeoIPService_Expecter{mock: &_m.Mock}
}

// CountryName provides a mock function for the type MockGeoIPService
func (_mock *MockGeoIPService) CountryName(ctx context.Context, ip string) (string, error) {
	ret := _mock.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for CountryName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, ip)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, ip)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeoIPService_CountryName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountryName'
type MockGeoIPService_CountryName_Call struct {
	*mock.Call
}

// CountryName is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *MockGeoIPService_Expecter) CountryName(ctx interface{}, ip interface{}) *MockGeoIPService_CountryName_Call {
	return &MockGeoIPService_CountryName_Call{Call: _e.mock.On("CountryName", ctx, ip)}
}

func (_c *MockGeoIPService_CountryName_Call) Run(run func(ctx context.Context, ip string)) *MockGeoIPService_CountryName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGeoIPService_CountryName_Call) Return(s string, err error) *MockGeoIPService_CountryName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGeoIPService_CountryName_Call) RunAndReturn(run func(ctx context.Context, ip string) (string, error)) *MockGeoIPService_CountryName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVPNParser creates a new instance of MockVPNParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVPNParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVPNParser {
	mock := &MockVPNParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVPNParser is an autogenerated mock type for the VPNParser type
type MockVPNParser struct {
	mock.Mock
}

type MockVPNParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVPNParser) EXPECT() *MockVPNParser_Expecter {
	return &MockVPNParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockVPNParser
func (_mock *MockVPNParser) Parse(vpnURL string) (vpnurl.SingBoxOutbound, error) {
	ret := _mock.Called(vpnURL)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 vpnurl.SingBoxOutbound
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (vpnurl.SingBoxOutbound, error)); ok {
		return returnFunc(vpnURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) vpnurl.SingBoxOutbound); ok {
		r0 = returnFunc(vpnURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vpnurl.SingBoxOutbound)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(vpnURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVPNParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockVPNParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - vpnURL string
func (_e *MockVPNParser_Expecter) Parse(vpnURL interface{}) *MockVPNParser_Parse_Call {
	return &MockVPNParser_Parse_Call{Call: _e.mock.On("Parse", vpnURL)}
}

func (_c *MockVPNParser_Parse_Call) Run(run func(vpnURL string)) *MockVPNParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVPNParser_Parse_Call) Return(singBoxOutbound vpnurl.SingBoxOutbound, err error) *MockVPNParser_Parse_Call {
	_c.Call.Return(singBoxOutbound, err)
	return _c
}

func (_c *MockVPNParser_Parse_Call) RunAndReturn(run func(vpnURL string) (vpnurl.SingBoxOutbound, error)) *MockVPNParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigStore creates a new instance of MockConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigStore {
	mock := &MockConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigStore is an autogenerated mock type for the ConfigStore type
type MockConfigStore struct {
	mock.Mock
}

type MockConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigStore) EXPECT() *MockConfigStore_Expecter {
	return &MockConfigStore_Expecter{mock: &_m.Mock}
}

// CreateBackup provides a mock function for the type MockConfigStore
func (_mock *MockConfigStore) CreateBackup(configPath string) (string, error) {
	ret := _mock.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(configPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(configPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(configPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigStore_CreateBackup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackup'
type MockConfigStore_CreateBackup_Call struct {
	*mock.Call
}

// CreateBackup is a helper method to define mock.On call
//   - configPath string
func (_e *MockConfigStore_Expecter) CreateBackup(configPath interface{}) *MockConfigStore_CreateBackup_Call {
	return &MockConfigStore_CreateBackup_Call{Call: _e.mock.On("CreateBackup", configPath)}
}

func (_c *MockConfigStore_CreateBackup_Call) Run(run func(configPath string)) *MockConfigStore_CreateBackup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigStore_CreateBackup_Call) Return(s string, err error) *MockConfigStore_CreateBackup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockConfigStore_CreateBackup_Call) RunAndReturn(run func(configPath string) (string, error)) *MockConfigStore_CreateBackup_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConfig provides a mock function for the type MockConfigStore
func (_mock *MockConfigStore) LoadConfig(path string) (*singbox.Config, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *singbox.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*singbox.Config, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *singbox.Config); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*singbox.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigStore_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockConfigStore_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - path string
func (_e *MockConfigStore_Expecter) LoadConfig(path interface{}) *MockConfigStore_LoadConfig_Call {
	return &MockConfigStore_LoadConfig_Call{Call: _e.mock.On("LoadConfig", path)}
}

func (_c *MockConfigStore_LoadConfig_Call) Run(run func(path string)) *MockConfigStore_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigStore_LoadConfig_Call) Return(config *singbox.Config, err error) *MockConfigStore_LoadConfig_Call {
	_c.Call.Return(config, err)
	return _c
}

func (_c *MockConfigStore_LoadConfig_Call) RunAndReturn(run func(path string) (*singbox.Config, error)) *MockConfigStore_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SaveConfig provides a mock function for the type MockConfigStore
func (_mock *MockConfigStore) SaveConfig(path string, cfg *singbox.Config) error {
	ret := _mock.Called(path, cfg)

	if len(ret) == 0 {
		panic("no return value specified for SaveConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *singbox.Config) error); ok {
		r0 = returnFunc(path, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigStore_SaveConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveConfig'
type MockConfigStore_SaveConfig_Call struct {
	*mock.Call
}

// SaveConfig is a helper method to define mock.On call
//   - path string
//   - cfg *singbox.Config
func (_e *MockConfigStore_Expecter) SaveConfig(path interface{}, cfg interface{}) *MockConfigStore_SaveConfig_Call {
	return &MockConfigStore_SaveConfig_Call{Call: _e.mock.On("SaveConfig", path, cfg)}
}

func (_c *MockConfigStore_SaveConfig_Call) Run(run func(path string, cfg *singbox.Config)) *MockConfigStore_SaveConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *singbox.Config
		if args[1] != nil {
			arg1 = args[1].(*singbox.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigStore_SaveConfig_Call) Return(err error) *MockConfigStore_SaveConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigStore_SaveConfig_Call) RunAndReturn(run func(path string, cfg *singbox.Config) error) *MockConfigStore_SaveConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigValidator creates a new instance of MockConfigValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigValidator {
	mock := &MockConfigValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigValidator is an autogenerated mock type for the ConfigValidator type
type MockConfigValidator struct {
	mock.Mock
}

type MockConfigValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigValidator) EXPECT() *MockConfigValidator_Expecter {
	return &MockConfigValidator_Expecter{mock: &_m.Mock}
}

// CheckConfig provides a mock function for the type MockConfigValidator
func (_mock *MockConfigValidator) CheckConfig(ctx context.Context, configPath string) error {
	ret := _mock.Called(ctx, configPath)

	if len(ret) == 0 {
		panic("no return value specified for CheckConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, configPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigValidator_CheckConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckConfig'
type MockConfigValidator_CheckConfig_Call struct {
	*mock.Call
}

// CheckConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - configPath string
func (_e *MockConfigValidator_Expecter) CheckConfig(ctx interface{}, configPath interface{}) *MockConfigValidator_CheckConfig_Call {
	return &MockConfigValidator_CheckConfig_Call{Call: _e.mock.On("CheckConfig", ctx, configPath)}
}

func (_c *MockConfigValidator_CheckConfig_Call) Run(run func(ctx context.Context, configPath string)) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigValidator_CheckConfig_Call) Return(err error) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigValidator_CheckConfig_Call) RunAndReturn(run func(ctx context.Context, configPath string) error) *MockConfigValidator_CheckConfig_Call {
	_c.Call.Return(run)
	return _c
}
