// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package useragent

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRand creates a new instance of MockRand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRand {
	mock := &MockRand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRand is an autogenerated mock type for the Rand type
type MockRand struct {
	mock.Mock
}

type MockRand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRand) EXPECT() *MockRand_Expecter {
	return &MockRand_Expecter{mock: &_m.Mock}
}

// IntN provides a mock function for the type MockRand
func (_mock *MockRand) IntN(n int) int {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for IntN")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockRand_IntN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntN'
type MockRand_IntN_Call struct {
	*mock.Call
}

// IntN is a helper method to define mock.On call
//   - n int
func (_e *MockRand_Expecter) IntN(n interface{}) *MockRand_IntN_Call {
	return &MockRand_IntN_Call{Call: _e.mock.On("IntN", n)}
}

func (_c *MockRand_IntN_Call) Run(run func(n int)) *MockRand_IntN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRand_IntN_Call) Return(n1 int) *MockRand_IntN_Call {
	_c.Call.Return(n1)
	return _c
}

func (_c *MockRand_IntN_Call) RunAndReturn(run func(n int) int) *MockRand_IntN_Call {
	_c.Call.Return(run)
	return _c
}
